name: Build Ballistica Server (Release)

on:
  push:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y libopenal-dev libsdl2-dev libvorbis-dev cmake \
                            clang-format rsync build-essential ninja-build git

    - name: Build BallisticaKit headless server
      run: CMAKE_BUILD_TYPE=Release make cmake-server-build

    - name: Rename binary
      run: mv build/cmake/server-release/staged/dist/ballisticakit_headless build/cmake/server-release/staged/dist/bombsquad_headless

    - name: Upload built server artifact
      uses: actions/upload-artifact@v4
      with:
        name: headless-release
        path: build/cmake/server-release/staged/dist/bombsquad_headless